using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

/*
 Programmer : Noah Ramones
 Description : This class is to roll the dice and display an image of the dice roll in the picture box
 */

namespace GameProject
{
    class Die
    {
        private int face;
        Random rand = new Random();
        public Image roll1 = new Bitmap(@"C:\Users\student\OneDrive - Monterey Trail High School DATA\GameProject\Pictures\cube1.jpg");
        public Image roll2 = new Bitmap(@"C:\Users\student\OneDrive - Monterey Trail High School DATA\GameProject\Pictures\cube2.jpg");
        public Image roll3 = new Bitmap(@"C:\Users\student\OneDrive - Monterey Trail High School DATA\GameProject\Pictures\cube3.jpg");
        public Image roll4 = new Bitmap(@"C:\Users\student\OneDrive - Monterey Trail High School DATA\GameProject\Pictures\cube4.jpg");
        public Image roll5 = new Bitmap(@"C:\Users\student\OneDrive - Monterey Trail High School DATA\GameProject\Pictures\cube5.jpg");
        public Image roll6 = new Bitmap(@"C:\Users\student\OneDrive - Monterey Trail High School DATA\GameProject\Pictures\cube6.jpg");

        public PictureBox diePic { get; set; } // picture box will be set when the instance of class is created

        public Die() // constructor for the class
        {
            face = rand.Next(6) + 1; // generates random number from 1 to 6
        }

        public int Face 
        {
            get { return face; }
            set { face = value; }
        }

        public int roll() // to generate another random number different from the original random number generated by die constructor
        {
            face = rand.Next(6) + 1; // generates random number
            return face; // return random number
        }

        /*public void scores()
        {

            if (face == 1)
            {
                score++;
            }
            if (face == 2)
            {
                score += 2;
            }
            if (face == 3)
            {
                score += 3;
            }
            if (face == 4)
            {
                score += 4;
            }
            if (face == 5)
            {
                score += 5;
            }
            if (face == 6)
            {
                score += 6;
            }

        }*/

        public void setDiePic() // decides which pic to show in picture box. Depends on number generated
        { 
            if (face == 1)
                diePic.Image = roll1;

            if (face == 2)
                diePic.Image = roll2;

            if (face == 3)
                diePic.Image = roll3;

            if (face == 4)
                diePic.Image = roll4;

            if (face == 5)
                diePic.Image = roll5;

            if (face == 6)
                diePic.Image = roll6;

        }

        public void setDiePic2() // decides which pic to show in picture box. Depends on number generated
        { 
            if (face == 1)
                diePic.Image = roll1;

            if (face == 2)
                diePic.Image = roll2;

            if (face == 3)
                diePic.Image = roll3;

            if (face == 4)
                diePic.Image = roll4;

            if (face == 5)
                diePic.Image = roll5;

            if (face == 6)
                diePic.Image = roll6;

        }
       
     
    }
}
